### ISSUE TITLE
Unable to Scrape Tags Information from Anilist

### ISSUE THREAD

**Issue by k3ltfalcon** [MangaManagerORG/Manga-Manager#217]
**Describe the bug**
The software cannot scrape Tags information from Anilist

**To Reproduce**
1. Add manga by selecting 'Open Files'.
2. Click 'Fetch Online'
3. It successfully scraped the information but not Tags information

**Expected behavior**
When I click 'Fetch Online', the software should scrape all information from Anilist.

**Screenshots**
Scraped the information but not Tags information
![image](https://github.com/user-attachments/assets/ba0b958a-2a4b-40e2-a2eb-759b54beb697)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 1.0.4

**Comment by jovaniedelacruz** [comment]
I'm also experiencing a worse version of this issue. Fetch Online can't even query the manga name against AniList. I tried it both on v1.0.4 and nightly_e5dd1ab.
Both MangaUpdates and more importantly AniList have errors when fetching online. I'm guessing the API with those sites have changed? I tried this with Bleach as well with similar results. Can verify that in AniList there are entries for these series.

```
Traceback (most recent call last):
  File "ExternalSources\MetadataSources\Providers\AniList.py", line 175, in _post
    return response.json()['data']['Media']
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-11-14 17:40:20,646 -                 root -    ERROR - Wrong data format recieved when parsing response json
Traceback (most recent call last):
  File "ExternalSources\MetadataSources\Providers\AniList.py", line 109, in _get_id_from_series
    content = cls._search_for_manga_title_by_manga_title(cinfo.series, "MANGA", {})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ExternalSources\MetadataSources\Providers\AniList.py", line 225, in _search_for_manga_title_by_manga_title
    raise MangaNotFoundError("AniList", manga_title)
src.Common.errors.MangaNotFoundError: AniList did not return any results for series name "Chainsaw Man"This may be due to a difference in manga series titles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ExternalSources\MetadataSources\Providers\AniList.py", line 175, in _post
    return response.json()['data']['Media']
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mckenna654** [comment]
Same issues here, can't fetch online... Is this program dead?

**Comment by majora2007** [comment]
This program has never pulled tags from AniList. The main developer seems to be a way, I'm a backup maintainer. The program is working fine for me.

**Comment by billsargent** [comment]
Are you still maintaining it? It hasnt been touched in years.

**Comment by majora2007** [comment]
This is no longer maintained but it's still functional. 

I would recommend using https://github.com/Ark1369/CBZ-Metadata-Manager
